### ISSUE TITLE
Missing information in scope statement

### ISSUE THREAD

**Issue by FewerFlaws** [Webreaper/Damselfly#111]
I had to dig into source code to figure out which image formats are supported.  It would be nice if this information was presented in the feature list.

At a glance it looks like client-side caching is used.  This is another item to present on the feature list.

A statement about access control would also be nice.  At the moment it looks like there is none.

**Comment by Webreaper** [comment]
Yes, I need to add supported image formats to the readme and website - thanks. More importantly, I need to list key formats which _aren't_ supported (e.g., HEIC, as mentioned in #17). 

Client-side caching isn't used explicitly, but yes, thumbs etc will be cached client-side by the browser. 

And whilst access control and user identity isn't explicitly mentioned in the docs, it is mentioned in #8. But I'll add a note in the Readme.
