### ISSUE TITLE
Moving files around doesn't seem to cause re-indexing

### ISSUE THREAD

**Issue by dsm1212** [Webreaper/Damselfly#146]
I had a folder where I had staged some files for cleaning up later. Some days later I moved the files (mv in linux) to another already existing folder and then deleted the staging folder. Nothing seems to have changed in damselfly. It still shows the deleted folder, I can browse the files there, etc. The files are not showing in the folder they were moved to. Is there something special about mv that avoids detection for changes to the index? I tried touching the files and it made no difference either.

**Comment by Webreaper** [comment]
This could be a number of things. 
1. Damselfly uses iNotify watchers to track changes in folders, and if you have a lot of folders you can hit the maximum number of watchers, and after that folders won't be watched. The docker image start script [attempts to fix this](https://github.com/Webreaper/Damselfly/blob/master/damselfly-entrypoint.sh#L10) but it's possible that if it can't execute that as root it won't work. You can check if the FileWatcher picked up the change by looking for log entries that say "`FileWatcher: adding to queue`".
2. I made a mistake with one of the recent releases and included a change which disabled the filewatcher creation. It's fixed now in the dev image, but I can't remember if I did another release (I think I did) - so please try a pull/update and see if that solves it. 
3. Another bug of which I'm not yet aware. :)

**Comment by Webreaper** [comment]
@dsm1212 Did you manage to get this resolved?
