### ISSUE TITLE
Support for Sony RAW

### ISSUE THREAD

**Issue by ikolsteren** [Webreaper/Damselfly#315]
Would be awesome to provide support for other RAW formats
I have attached a file from the Sony A6400 as well
[20210728-182129-2.ARW.zip](https://github.com/Webreaper/Damselfly/files/7584245/20210728-182129-2.ARW.zip)

**Comment by ikolsteren** [comment]
Olympus RAW
[20210619-150824.ORF.zip](https://github.com/Webreaper/Damselfly/files/7584273/20210619-150824.ORF.zip)

**Comment by Webreaper** [comment]
Thanks! This should work - will test, and assuming it does, will try and get it into the next release.

**Comment by ikolsteren** [comment]
Nikon RAW


> Thanks! This should work - will test, and assuming it does, will try and get it into the next release.

Perfect, I have a Nikon one but can't seem to zip and attach it

**Comment by Webreaper** [comment]
Okay, so ORF definitely works. SkiaSharp (which I mainly use for thumbs) doesn't support ARW, so I tried using ImageMagic (which is the fallback option for more obscure image formats), but it doesn't seem to like it. Will do a bit of research though. 

Can you email the Nikon one to me? info@damselfly.info

**Comment by Webreaper** [comment]
Okay, I've enabled ORF and NEF support - that'll be available in the next release. 

For Sony ARW it's more complex, so I've raised another issue here: https://github.com/Webreaper/Damselfly/issues/316

**Comment by ikolsteren** [comment]
Awesome, looking forward to playing with then it comes out
Thank you

**Comment by Webreaper** [comment]
Just released: https://github.com/Webreaper/Damselfly/releases/tag/2.8.0-beta
