### ISSUE TITLE
Unable to start Azure service

### ISSUE THREAD

**Issue by anupammukherjee** [Webreaper/Damselfly#332]
Thanks for the nice server, I have been using it quite a bit recently, although I’m new to both synology and the world of self hosting.

I get the following error:
[9:42:36.868-.NET ThreadPool Worker-ERR] Unable to start Azure service: Value cannot be null. (Parameter 'source')
After restart:
[15:20:18.034-.NET ThreadPool Worker-ERR] Unable to start Azure service: Value …
etc.

This used to work earlier(Maybe ~15 days ago)
I have tried the following:
-Restart
-Regenerating and using a different Azure faceAPI endpoint key.
-Updating damselfly to the latest version.

Nothing has worked so far.

**Comment by Webreaper** [comment]
Please attach (or email to info@damselfly.info) a full log - there's not enough to go on from the snippet you posted there.

**Comment by anupammukherjee** [comment]
> Attached here:

[Damselfly-20220111.log](https://github.com/Webreaper/Damselfly/files/7848482/Damselfly-20220111.log)

**Comment by anupammukherjee** [comment]
Thanks for looking into it!
