### ISSUE TITLE
Allow using CTRL to select individual images

### ISSUE THREAD

**Issue by collowe** [Webreaper/Damselfly#348]
SHIFT key allows several images to be selected next to each other, which you can then process (keywords, refresh etc).  Would be great to be able to hold CTRL and select images that are not next to each other for processing.

Currently you have to perform multiple batches of updates

**Comment by Webreaper** [comment]
That's already supported - I use that functionality all the time. Have you actually tried it?

If it doesn't work for you, what platform are you on (Mac/Linux/Windows), which version, which browser, etc., please.

**Comment by collowe** [comment]
Ah ok - thought it was unusual that it wasn't supported but shift was.  I'm using Firefox on Ubuntu 20.04,  Raised it as I was testing earlier and it didn't work, just retried and it definitely doesn't work.

**Comment by Webreaper** [comment]
Can you try Chrome please and let me know if the behaviour is any different?

**Comment by Webreaper** [comment]
If you want to try it out, you can pull `webreaper/damselfly:dev` in about 20 mins.

**Comment by Webreaper** [comment]
Should be fixed in v2.9.5
