### ISSUE TITLE
Azure Image Recognition not Running

### ISSUE THREAD

**Issue by bericha** [Webreaper/Damselfly#353]
Set up the Microsoft Azure Face API via the Damselfly/Microsoft instructions.

Input the Azure API endpoint url and API key into Damselfly.

Saw 4 requests hit the API endpoint via the Monitoring portal in Azure. Since then, I have seen zero requests. The Damselfly instance will generate a few requests to the endpoint if I restart the docker.

Edit: daily log attached for today:
[Damselfly-20220422.log](https://github.com/Webreaper/Damselfly/files/8543139/Damselfly-20220422.log)

**Comment by bericha** [comment]
On my instance It appears that the Azure Face API only runs on photos that are put into Damselfly after the API is enabled. Is this normal behavior? If so, is there anyway to get the API to scan pre-existing photos?

**Comment by Webreaper** [comment]
Sure, right click on a selected set of images, or a folder, or "All folders" and choose refresh. Then check the AI checkbox and it'll reprocess them all.

**Comment by bericha** [comment]
Thank you! I'm processing now.

Will definitely be sending a donation your way sir.

**Comment by Webreaper** [comment]
Thank you!
