### ISSUE TITLE
Browse Folder structure

### ISSUE THREAD

**Issue by moritzfl** [Webreaper/Damselfly#355]
I am glad to have found this application as I used to be an avid Picasa user back in the day. I am truly amazed at what it can do specifically regarding person and object recognition and searching.

However, there is a feature that I am missing from Picasa. Picasa offered a folder view for browsing the images (see screenshot). For me this is a must-have feature for my primary photo application given that the folder structure is something that can be shown and navigated on any device - even devices without any sophisticated photo applications (for example FE File Explorer on my AppleTV which I use to view photos there).

If I didn't miss anything and Damselfly does not yet provide this feature, I would very much appreciate if this feature was considered for implementation.

![picasa-projects2](https://user-images.githubusercontent.com/18644803/170437671-0e183a88-1f63-46d5-907d-a652611629d8.jpg)

**Comment by moritzfl** [comment]
Sorry - I guess I was a bit imprecise there but I think you understood me correctly. I specifically had the hierarchical structure in mind (as shown in the screenshot).

Let me illustrate with an example why the hierarchical view is important to me.
Usually we name folders after certain events e.g. "Holiday Norway 2022" and in there would be subfolders for each person that contributed photos (i.e. moritz, my wife, my father etc.). So there are many folders with the same name underneath a top level folder with a different name.
If there is no specific event linked to photos, we generally put them in a "Family"-Folder with subfolders for each months and within those subfolders we use the same pattern for each persons photos. So our whole organization system is folder based with different levels of depth for the subfolders. And many of the "leaf-folders" that actually contain pictures do not have a unique name.

**Comment by tkafka** [comment]
+1 here if I may - my folder structure is hierarchical, because of multiple contexts (family, friends, work - each having subfolders with events, and sometimes those are split by photographers)

**Comment by tkafka** [comment]
@Webreaper Whoa, awesome!!! At a first try it seems to work really well! Once you get the folder sorting sorted :), it will be pretty much perfect! Thank you!

**Comment by tkafka** [comment]
Maybe one nice enhancement would be if the tree mode could be saved in a cookie, so that once I switch to it, it stays on. But I guess this could be a larger story with saving of various preferences (thumbnail size, current folder and scroll position ...)

**Comment by Webreaper** [comment]
It should remember the setting (tree or list) in a user setting, but you may have to be logged in. I also plan to add some settings so that it'll remember the expanded state of individual folders between sessions. I *think* the scroll position should already be remembered, but I'll do some additional testing.

**Comment by tkafka** [comment]
Awesome! Thanks for clearing that up, I use Damselfly on a home network without any login, so that's what I've been missing.

**Comment by Webreaper** [comment]
It should set preferences for all users if you don't have auth/login set up, so I'll investigate that. 

Sorting will be in the latest dev image in about 10 mins. Then I just need to add:

- Option to switch between name and date sorting
- Option to switch between ascending and descending
- Persistence of the expanded state between sessions

Once they're done, I'll push a new release.

**Comment by Webreaper** [comment]
Those are done now. I may add some buttons/icons to toggle the sort settings and tree view option, but the functionality is now there.

Can you re-pull the dev image and give it a go and see if everything works as expected? If so I'll tidy it up and do a release.
