### ISSUE TITLE
Azure Face API always responds 429

### ISSUE THREAD

**Issue by gmartens** [Webreaper/Damselfly#412]
I set up Azure Faces with the key and endpoint. 
When I run AI processing on Damselfly, all Azure requests are responded with 429, which is rate limiting.
I am paying for Azure Faces so I shouldn't be rate limited. I even get this response when testing a refresh of just one image.
Sometimes this will show up in Damselfly's logs, other times it will not. But in the Azure portal the number of requests is equal to the number of error 429s. The only consistent error I get in Damselfly is:
`Unable to start Azure service: Value cannot be null. (Parameter 'source')`
I've tested Azure Faces using Microsoft's API example tool, and it works fine.
Also have been testing with the new Dev image you released, which had no change.

**Comment by Webreaper** [comment]
Seems like others are hitting similar: https://stackoverflow.com/questions/33282321/azure-management-api-429-too-many-requests - you might need to ping MSFT. 

It seems their rate-limiting is a bit flawed in a lot of ways, for example: https://docs.microsoft.com/en-us/answers/questions/496094/azure-face-throttling-inconsistent-behaviour.html

**Comment by rexdavid** [comment]
I am seeing this too

**Comment by rexdavid** [comment]
Reached out to MS , they send me these links :

 

Thank you for reaching Azure free trial chat support team.

 

Please refer the below documents 

https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/429-too-many-requests-errors
https://learn.microsoft.com/en-us/azure/logic-apps/handle-throttling-problems-429-errors
https://learn.microsoft.com/en-us/answers/questions/738983/error-429-on-audio-export-from-azure-text-to-speec.html
https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/concepts/data-limitshttps://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-quotas-and-limits
 
Please let us know if the suggestions shared in email were helpful.
If you can update the issue status , that will be great. 
 
Feel free to reach us back on live chat if you need any further assistance. We'll be glad to help you!

Thanks and Regards
Azure free trial chat support team

**Comment by DennisFaucher** [comment]
Also can't get past the "Unable to start Azure service: Value cannot be null. (Parameter 'source')" error and no face recognition is occurring in the log. Just for fun, I created a paid (not free) tier of Azure Face API and turned off throttling in Damselfly. Same error. I'll keep guessing and trying.

**Comment by Webreaper** [comment]
Did this get resolved in the end?
