### ISSUE TITLE
Logged out screen still shows images

### ISSUE THREAD

**Issue by gmartens** [Webreaper/Damselfly#414]
If the "Force users to login before accessing Damselfly" option is selected, users can still see images on the home page before signing in.
(I think) this wasn't the case before I updated to the Dev branch.
I'd like no images or content to show up at all unless signed in.

**Comment by Webreaper** [comment]
Done some work on this, but still some stuff to improve.

**Comment by Webreaper** [comment]
Just committed a fix for this - give dev a pull in about 10 minutes when the latest build completes, and it should be good.
