### ISSUE TITLE
4.0.0 issues

### ISSUE THREAD

**Issue by Tyen3** [Webreaper/Damselfly#425]
Here's a brief list of issues I've seen with 4.0.0 (pulled down the latest :dev container):

1. When logging into a brand new instance, going to the gears/settings prompts you to create an admin account. Filling out the form creates the account, but once created there is no visual confirmation that the account was created
2. No way to see a list of users when logged in as admin
3. When scrolling a folder then viewing an image, hitting the esc key or clicking back brings you back to the top of the images list rather than bringing you back to where you were viewing in the list. This makes viewing large folders difficult. 3.0.0 works as expected. Tested with the latest versions of Firefox and Chrome, same behavior.
4. Exif version bundled in the container is a bit old (ExifVersion: v11.88 is bundled, 12.45 is the latest)

**Comment by Webreaper** [comment]
Thanks for these. All known issues which are on my list, but useful to have them tracked explicitly here!

**Comment by Tyen3** [comment]
> Thanks for these. All known issues which are on my list, but useful to have them tracked explicitly here!
> 
> Can you elaborate on 2? You should be able to see all users in the User Admin tab on the settings screen.

I just pulled the latest :dev container to re-test this. With a clean launch (no preexisting database or thumbs), clicking on the gears icon brings me to a form to create an admin user, but User Roles is pre-selected to User, and clicking on the roles dropdown brings up an empty dropdown.

**Comment by Webreaper** [comment]
Sorry, yes, I was halfway through this, but it's not 100% complete. :(

**Comment by Webreaper** [comment]
Exiftool v12.48 now.

**Comment by Webreaper** [comment]
Okay, so I think it just need to tidy up the initial user setup (so number one in your list). How is everything else looking?

**Comment by Tyen3** [comment]
OK, I ran through the previous issues. I am still experiencing the first issue, and now it seems the account isn't actually created. All of the other issues no longer occur, thank you!

Here's how to reproduce the first issue:

1. Fresh docker instance pointing to a small set of photos
2. Click on the gears icon and the panel to create a new admin user pops up.
3. Fill out details and click "Create User", but the window never dismisses, and it doesn't appear the account is actually created. 

![image](https://user-images.githubusercontent.com/107116755/199958338-9aacf8ad-8eef-4256-9c39-605c5c1fc4e7.png)

**Comment by Webreaper** [comment]
Thanks. You should find that the user account is created - I just need to fix the UI so that it updates the statusbar, and dismisses the dialog. :)

**Comment by Webreaper** [comment]
Okay, this should be fixed now - I've cleaned up the user creation process and done some tidying. Just doing some final testing now, but I'm going to mark this as done.
