### ISSUE TITLE
AppImage download link doesn't download

### ISSUE THREAD

**Issue by samteezy** [Webreaper/Damselfly#450]
After I heard about the v4.0.0 release I decided to try running this again on my Synology. I kept my old /thumbs folder but deleted the db files and started from scratch. I've got the docker running and am accessing it at a local IP address. When I go to download the client-side AppImage, a blank browser tab is displayed but nothing downloads. However the Win and Mac download links do work properly.

**Comment by Webreaper** [comment]
Ooh, thanks - sounds like I broke something. Will take a look and also upload the artifacts to the github release.
