### ISSUE TITLE
MacOS desktop app stuck on initial screen

### ISSUE THREAD

**Issue by tschweitzer** [Webreaper/Damselfly#452]
I installed the 4.0.0 version, went to the info screen, then the damselfly desktop tap, downloaded and started the MacOS app. The initial screen show the two inputs for URL and images folder. I filled both but the "Save" button does not get enabled, respective on clicking nothing happens.

**Comment by Webreaper** [comment]
That usually means you haven't specified a valid url or folder for the settings. Can you check you don't have trailing spaces or invalid characters (eg from copy/paste)?

**Comment by tschweitzer** [comment]
Thanks for the super swift reply. My url is like `http://192.168.xx.yy:49157`. My pictures path is like `/Users/MyUsername/Pictures`. No special chars, no spaces in between or at the beginning or end.

**Comment by Webreaper** [comment]
I just tried downloading a fresh copy and I can repro. Will look at a fix!

**Comment by Webreaper** [comment]
This should be fixed with the latest dev push (currently building, should be ready in about 15 mins). Can you give it a try and let me know if it solves the issue? `docker pull webreaper/damselfly:dev`. :)
