### ISSUE TITLE
Have keyboard shortcut for "mark for basket"

### ISSUE THREAD

**Issue by tschweitzer** [Webreaper/Damselfly#453]
While being in single image view mode where left and right keys work for navigating between images: It would be awesome to have a keyboard shortcut to mark an image (move it to the basket).

**Comment by Webreaper** [comment]
Good idea! How about space to toggle "in / out of basket"?

**Comment by tschweitzer** [comment]
That would work great for me.

**Comment by Webreaper** [comment]
This is available in the dev version now (`docker pull webreaper/damselfly:dev`) and I'll push it out in a small patch release for 4.0.0 in the next few days.

**Comment by tschweitzer** [comment]
Just gave it a try and works great. Amazingly quick work! Thanks for that!!!
