### ISSUE TITLE
Error after upgrade to latest version

### ISSUE THREAD

**Issue by collowe** [Webreaper/Damselfly#456]
Hi - upgraded my version to 4 and am getting the following error in the log file :

An exception occurred while iterating over the results of a query for context type 'Damselfly.Core.Models.ImageContext'.

My logs are full of the same message - it's erroring every 30 seconds

Further investigation looks like the db migrations are failing:

21:07:16.647 | WRN | Migrations failed  with exception: Microsoft.Data.Sqlite.SqliteException (0x80004005):  SQLite Error 19: 'FOREIGN KEY constraint failed'.
21:07:16.634 | ERR | Failed executing DbCommand (0ms) [Parameters=[
21:07:15.131 | INF | Running Sqlite DB migrations...

Another error that probably stems from the db migration issue?

21:07:19.542 | ERR | Exception during  caching/enrichment: Microsoft.Data.Sqlite.SqliteException (0x80004005):  SQLite Error 1: 'no such column: f.ParentId'.

It doesn't display any photos from my NAS - all the same settings in my docker-compose as with the previous version.  Any hints?

**Comment by collowe** [comment]
Update on this, I've moved the db folder and so it's running tasks and regenerating the DB from scratch.  I'm ok with this as a solution tbh, but if there's another option would be good to review.

**Comment by Webreaper** [comment]
Thanks, that was going to be my suggestion.

If there isn't anything sensitive in it, would you be able to send me the DB zipped up so I can take a look? If not, at least the full log file would be useful. Thanks!
