### ISSUE TITLE
Error when attempting to tag a face identified as "Unidentified"

### ISSUE THREAD

**Issue by whoopn** [Webreaper/Damselfly#459]
Error:
`System.NullReferenceException: Arg_NullReferenceException
   at Damselfly.Web.Client.Shared.Dialogs.NameDialog.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

Happens when I click on the "Unidentified Face".  

Damselfly v4.0.2.

Is there a setting I need to turn on?

**Comment by Webreaper** [comment]
Think it's just a bug - investigating....

**Comment by Webreaper** [comment]
Can you try pulling `webreaper/damselfly:dev` and see if that stops the exception?

**Comment by whoopn** [comment]
It takes a while for the dev to get where the non-dev is.  The filter for tagged faces also seems like it doesn't filter right (or I dont know how to use it).  I'll let you know if it resolves it.

**Comment by whoopn** [comment]
Same error:

System.NullReferenceException: Arg_NullReferenceException
   at Damselfly.Web.Client.Shared.Dialogs.NameDialog.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   
[Damselfly-20221217.log](https://github.com/Webreaper/Damselfly/files/10253151/Damselfly-20221217.log)

**Comment by dhthwy** [comment]
I tested this in develop branch and it was still throwing an exception in UpdateName in ImageRecognitionService. A few lines below I see:

```
if (faceObject.Person == null)
{
        faceObject.Person = new Person();
        db.People.Add(faceObject.Person);
}
```

So I am assuming the exception is a mistake?  I created a pull request #465 to address this, and it now works for me. Nice work btw!

**Comment by Webreaper** [comment]
Exception is indeed a mistake. Good spot - thanks for fixing! :)
