### ISSUE TITLE
XMP metadata not read

### ISSUE THREAD

**Issue by dominformant** [Webreaper/Damselfly#460]
For all of my raw images, no metadata is shown in Damselfly, even if xmp sidecar files exist. I tried both `filename.ext.xmp` and `filename.xmp` but neither of those seems to be read. Is there any configuration that must be activated in order to read the sidecar files?

**Comment by dominformant** [comment]
I tried to find a reason for that, but as I have absolutely no experience with dotnet, I have some questions:

1. As far as I found out, metadata is extracted from the image files using [metadata-extractor-dotnet](https://github.com/drewnoakes/metadata-extractor-dotnet), and xmp sidecar files are not considered yet, right? However, the developer suggests using [xmp-core-dotnet](https://github.com/drewnoakes/xmp-core-dotnet) for sidecar files. Would it be much work to add support for sidecar files? I am also willing to try  to work on it, however, I'm still not sure how everything works so it would probably take a lot of time...
2. If I'm right that metadata-extractor-dotnet is used for metadata extraction, I'm wondering why I don't even see basic metadata (like creation time or image size) for NEF raw files, which should be supported by metadata-extractor-dotnet. Is there any option to debug the metadata extraction process?

**Comment by Webreaper** [comment]
Can you attach one of your XMP files and when I get time I'll debug and fix it.

**Comment by dominformant** [comment]
Thanks for your fast reply again, I attached an image and the according sidecar file. I had to zip it, as the file types are not supported by Github. Hope the files help you.
I wish you a happy last christmas day.
[DSC_4312.zip](https://github.com/Webreaper/Damselfly/files/10300674/DSC_4312.zip)

**Comment by Webreaper** [comment]
This should be better now.
