### ISSUE TITLE
Updated Rating is not detected by Damselfly 

### ISSUE THREAD

**Issue by martinhelmer** [Webreaper/Damselfly#467]
steps:
1. linux command line: `exiftool -Rating=2 [img]`
2. Select [img] in Damselfly, right click -> Refresh
2.1 select all 4 options (just to be safe)
3. wait for the re-scan to take place.
Rating is not updated in Damselfly
Modifying other fields, such as Caption-Abstract works.

**Comment by martinhelmer** [comment]
my pictures are on a different server, mounted with sshfs on the server that runs damselfly. however, since updating other pieces of metadata works, that might not be the issue.

**Comment by martinhelmer** [comment]
Apparently my command uses group XMP instead of EXIF by default. 
`exiftool -EXIF:Rating=2` fixes the problem

**Comment by Webreaper** [comment]
Perhaps I could add a feature to read the rating from XMP if no rating is found in exif. Will take a look.
