### ISSUE TITLE
Thumbnails of L and XL size are bigger than the original photo

### ISSUE THREAD

**Issue by ForeverKetone** [Webreaper/Damselfly#469]
Hi there!

Decided to give this project a try and noticed that L and XL thumbnails are even bigger in resolution (and size as well) than the original photo. Sometimes the size difference between the original photo and XL thumbnail is around 5x, which does not seem ok.

Here's a screenshot:
![damselfly](https://user-images.githubusercontent.com/67862325/220270089-334483ff-7b10-4cf2-8342-b3ab9e469a6b.png)

**Comment by Webreaper** [comment]
Good spot. That's pretty dumb, isn't it?!

Thanks, will look and fix - it certainly shouldn't happen. Out of interest, could you share the original photo that was larger? It's easier for me to test if I have an example. 

If you don't want to post here, you can email to info@damselfly.info :)

**Comment by ForeverKetone** [comment]
Yeah, sure, I packed my two example photos and their xl thumbs in archive below:
[two_photos_and_xl_thumbs.zip](https://github.com/Webreaper/Damselfly/files/10800317/two_photos_and_xl_thumbs.zip)

The difference seems clear when comparing two photos in a graphical editor:
![comparison](https://user-images.githubusercontent.com/67862325/220527979-9bb696c8-11b4-4d3b-98a0-3817f4b24e82.png)

Damselfly's version is v4.0.3.0, installed via [docker-compose as described here](https://hub.docker.com/r/webreaper/damselfly).
