### ISSUE TITLE
Issues debugging the app in Visual Studio

### ISSUE THREAD

**Issue by neozhu** [Webreaper/Damselfly#475]
I really like this project and I would like to learn more about it. However, I am having trouble debugging it in Visual Studio. Whenever I select Damselfly.Web.Server to run(debug), it crashes. Can someone please help me with this issue and advise me on what to look out for?

**Comment by Webreaper** [comment]
Firstly, "it crashes" doesn't really help much in identifying what's going wrong. Secondly, you need to provide more info - what OS, what IDE, and anything else. Do you have the right .Net SDKs installed?

I can't really spend much time helping you debug it though, as I'm finding little enough time to develop it myself at the moment. It _should_ just run once you clone the repo. Have you provided a command-line arg?

**Comment by neozhu** [comment]
Thank you very much for your prompt response. I'm using Visual Studio 2022 17.5.5 on Windows 11 with .NET 6.0/7.0 installed. The compilation process goes smoothly, but I'm encountering difficulties running the application. I have attempted running it as HTTPS/IIS Express/Damselfly.Web.Server, but none of these options seem to work.
<img width="485" alt="image" src="https://github.com/Webreaper/Damselfly/assets/1549611/c0db7cce-1c05-4022-920b-1a0518d99262">

**Comment by neozhu** [comment]
Did you use Docker Compose to debug the project? Typically, in a project, a Dockerfile configuration and a docker-compose.dcproj file are written to run Docker debugging.

**Comment by Webreaper** [comment]
No, I don't debug in docker. It just runs as a normal blazor project.

You might want to try debugging with Chrome rather than IIS express, because Damselfly uses Kestrel so doesn't need IIS.
