### ISSUE TITLE
Tag updates to images shouldn't overwrite CreateDate of image

### ISSUE THREAD

**Issue by yatzin** [Webreaper/Damselfly#485]
I just ran damselfly against my entire collection going back to 2008 (41k photos) and had it update all my createdate's to the day the auto tagged item was added.  Luckily I had a backup to restore the images but I did stop using damselfly as this is a dealbreaker for me.

**Comment by Webreaper** [comment]
Sorry, but that's not correct. It doesn't work that way at all. In fact, adding the ability to update exif data for images is not something I've implemented yet.

So you're either misunderstanding what happened, or something else is going on.
