### ISSUE TITLE
Damselfly not reading correct taken date from image

### ISSUE THREAD

**Issue by vishvish** [Webreaper/Damselfly#496]
Damselfly Version: v4.0.7.0 

I have a bunch of RAW images as DNGs that were taken in 2009 but modified by copying in 2023.

Within the Damselfly GUI, they appear as 2023 images.

Example Screenshot:

<img width="2121" alt="Screenshot 2023-09-28 at 00 40 44" src="https://github.com/Webreaper/Damselfly/assets/184423/70e61d2e-a1b1-4cdf-9547-24e6a88798bd">

ExifTool with the Canon output:

        ➔ exiftool -canon _MG_8171.dng
        File Name                       : _MG_8171.dng
        Camera Model Name               : Canon EOS 5D Mark II
        Date/Time Original              : 2009:06:08 16:45:55
        Shooting Mode                   : Aperture-priority AE
        Shutter Speed                   : 1/125
        Aperture                        : 7.1
        Metering Mode                   : Evaluative
        Exposure Compensation           : 0
        ISO                             : 200
        Lens                            : 50.0 mm
        Focal Length                    : 50.0 mm
        Image Size                      : 5792x3804
        Quality                         : RAW
        Flash                           : Off, Did not fire
        White Balance                   : Auto
        Focus Mode                      : AI Focus AF
        Contrast                        : Normal
        Sharpness                       : 3
        Saturation                      : Normal
        Color Tone                      : Normal
        Color Space                     : Adobe RGB
        Long Exposure Noise Reduction   : Auto
        File Size                       : 20 MB
        File Number                     : 100-8171
        Drive Mode                      : Continuous Shooting
        Owner Name                      :
        Serial Number                   : 0230112509

Here are some more details from ExifTool about this file:

        ExifToolVersion                 : 12.60
        FileName                        : _MG_8171.dng
        FileModifyDate                  : 2023:09:28 00:40:59+02:00
        FileAccessDate                  : 2023:09:28 00:41:13+02:00
        FileInodeChangeDate             : 2023:09:28 00:41:11+02:00
        ExifByteOrder                   : Little-endian (Intel, II)
        Make                            : Canon
        Model                           : Canon EOS 5D Mark II
        StripOffsets                    : 115496
        RowsPerStrip                    : 171
        StripByteCounts                 : 131328
        ModifyDate                      : 2009:06:08 16:45:55
        DateTimeDigitized               : 2009:06:08 16:45:55.45+05:30
        ExifVersion                     : 0221
        DateTimeOriginal                : 2009:06:08 16:45:55
        CreateDate                      : 2009:06:08 16:45:55

**Comment by Webreaper** [comment]
The metadata scanning is probably picking up the date from the wrong field when parsing a DNG. I'll have a look. Any chance you could email me the image, so I can test? (mark@otway.com). Thanks!

**Comment by vishvish** [comment]
Will do when I'm back at my Mac. I noted that ExifTool doesn't do the reading of data and didn't see DNG support explicitly from the other library.

**Comment by vishvish** [comment]
Image sent - 20MB (small by modern standards!)

**Comment by Webreaper** [comment]
Thanks! I've pushed a fix - if you want to give it a try, you can pull `webreaper/damselfly:dev`. 

Be aware that there's a few other enhancements that are mid-development in there, but nothing that would put your pics at risk.

**Comment by Webreaper** [comment]
Pushing a patch release with this as 4.0.8.

**Comment by vishvish** [comment]
Was just pulling dev and saw the 4.0.8 image arrive. Thanks!

**Comment by vishvish** [comment]
Brief and early update - Damselfly appears to not be reading any DNG images now, but I'm going to let it sit overnight and have a think.

**Comment by Webreaper** [comment]
Oh, that's not good. Give it time to fully index and touch a couple to ensure it rescans the metadata. Let me know!

**Comment by Webreaper** [comment]
I just upgraded my 'prod' install to 4.0.8 and the test image you sent me has indexed fine with the correct date.

**Comment by vishvish** [comment]
Something has gone awry, but I don't know what, so I'm going to stop the container, move or delete the existing docker volume contents and restart the container, reset the system and see what it does about the reindexing. Also going to check out all the env variables available in case I want to tweak the config this time.
