### ISSUE TITLE
Q: Will Damselfly learn / re-train from my existing tags?

### ISSUE THREAD

**Issue by arkonbob** [Webreaper/Damselfly#498]
I have a large-ish collection of photos (everything I've shot over the last couple of decades) which I have sorted in Digikam and tagged in detail. I've been poring over the documentation and one thing isn't clear to me; will Damselfly learn or re-train itself from these tags? You've mentioned creating and adding additional detection models in the docs, but I wondered if Damselfy continually updates it's own model and retrains itself from existing tags and manually entered tags?

**Comment by Webreaper** [comment]
No, Damselfly has no training mechanism, and I'm not planning to add one. It relies on pretrained models.
