### ISSUE TITLE
Release 4 running as windows binary (not docker)

### ISSUE THREAD

**Issue by gabryk91** [Webreaper/Damselfly#499]
Hi, I know you don't do support for installations that doesn't use docker, but I just need a little info I guess it's easy for you: I downloaded the exiftool Windows executable from here [https://exiftool.org/index.html ](https://exiftool.org/index.html ) and I see that it's not an installer but it's a command tool, so I guess it has to be placed inside the folder structure of damselfly or in some specific position on C:\
Can you help me with that? Thank you

**Comment by gabryk91** [comment]
Ok I just copied exiftools.exe in the root folder of damselfly and it's working. I have now the same issue with Imagemagik

**Comment by Webreaper** [comment]
You'll have to set up ImageMagick on your Windows box, and ensure it's accessible to execute by Damselfly. I can't help with that, sorry.
