### ISSUE TITLE
Support Sony .ARW RAW files

### ISSUE THREAD

**Issue by acrow-geo** [Webreaper/Damselfly#509]
I have a few thousand images taken with a Sony A7 rIII and A7 rIV - these files have a .arw extension and are supported by the usual Linux RAW libs and utilities - any chance of adding support for them please?

I replied to you on Reddit a couple of days ago BTW.

**Comment by Webreaper** [comment]
I think they should work - I've added the file extension and pushed it to a dev build.

When this finishes https://github.com/Webreaper/Damselfly/actions/runs/7602206891 can you try dev (pull `webreaper/damselfly:dev`). If it doesn't work, can you attach a sample image for me to test?

**Comment by acrow-geo** [comment]
I will look when I can - I'm cooking Sunday dinner right now!

**Comment by Webreaper** [comment]
Actually, I found some test images here https://www.photographyblog.com/previews/sony_a7s_iii_photos and they don't work, so I need to investigate more....

**Comment by acrow-geo** [comment]
Seems to be picking up the images at least. Thumbnails not being made though.

**Comment by Webreaper** [comment]
Yeah, it'll pick up the images once I enable that file extension. But it's not much use until I can find a decoder that can generate the thumbs!

I'll update when I've solved.

**Comment by acrow-geo** [comment]
Thanks mate, much appreciated!

**Comment by Webreaper** [comment]
Okay, tested this morning, and I have it working now. Try pulling `webreaper/damselfly:dev` and let me know if it works.
