### ISSUE TITLE
Logging in via default theme

### ISSUE THREAD

**Issue by drycounty** [Webreaper/Damselfly#510]
Not sure if this is a known issue already, but after installing this via Docker on synology, the default theme was the dark green.  I cannot see the login/password as the background is black, and the text is also black.  Perhaps if the default theme were grey, it would allow you to see if the fields are entered.

**Comment by Webreaper** [comment]
Never seen that before! If you press Shift-refresh does it work better?

Also, you might want to try pulling `webreaper/damselfly:dev` - it's got a lot of fixes including some around themes.

**Comment by drycounty** [comment]
trying the dev release didn't fix -- here's a screenshot after switching themes.  The only way to view any content on the page is to highlight/scroll.

I'm attempting this via Synology 423+ w/18GB of RAM, but another friend has seen the same behavior with the latest release on a Mac Pro (32GB RAM).

<img width="1484" alt="Screenshot 2024-03-05 at 9 17 12 AM" src="https://github.com/Webreaper/Damselfly/assets/35578660/cc4fd790-c4d2-4ee5-9484-0f99bd7afdc1">

**Comment by Webreaper** [comment]
I think I have a fix for this now.
