### ISSUE TITLE
Support for Canon's C-RAW/CR3 

### ISSUE THREAD

**Issue by christoph93** [Webreaper/Damselfly#516]
Hi, I have a mix of .cr2 and .cr3 files in my library. The cr2 files are being imported fine, but cr3 are not.
I understand that RAW image processing is done by external libraries, but I would like to request support for Canon C-RAW files as I have not seen an open issue for it yet.

Thanks!

**Comment by Webreaper** [comment]
Can you attach a sample cr3 file or email me one to mark@otway.com please? 

It's likely already supported - I may just need to add the file extension....

**Comment by christoph93** [comment]
Here two examples for the CR3 files: https://drive.google.com/file/d/1p4oJCD8Xs2XpAIlNWBs6V9Hx7LtvL48W/view?usp=drive_link

**Comment by Webreaper** [comment]
Fixed in latest dev version.

**Comment by Webreaper** [comment]
Hey @christoph93 is CR3 working for you with the 4.1.2 release? Got a bug report that it's not working (see #520) so wanted to check - and verify which OS you're running on?

**Comment by christoph93** [comment]
@Webreaper 
I think it's working on 4.1.3 but not on 4.1.2.

19:55:57.102 | ERR | Failed commandline  was: convert  -define jpeg:size=120x120  "/pictures/Canon/Random/IMG_0674.CR3" -quality 90 -unsharp  0.5x0.5+1.25+0.0 -thumbnail 120x120 -auto-orient  "/thumbs/Canon/Random/IMG_0674_s.JPG"

19:55:57.101 | ERR | Conversion failed. Unable to start process: Failed

**Comment by Webreaper** [comment]
Thanks, yes, that's expected.
