### ISSUE TITLE
Failed conversion on CR3 files

### ISSUE THREAD

**Issue by terath199** [Webreaper/Damselfly#520]
Receiving the following error in the logs on all .CR3. CR2s are processing perfectly. 

[08:14:31.845-.NET TP Worker-ERR] Failed commandline was: convert  -define jpeg:size=120x120 "/pictures/Matt/3-13-24_2/IMG_0684.CR3" -quality 90 -unsharp 0.5x0.5+1.25+0.0 -thumbnail 120x120 -auto-orient "/thumbs/Matt/3-13-24_2/IMG_0684_s.JPG" 

Failed commandline was: convert -define jpeg:size=120x120 "/pictures/Matt/3-13-24_2/IMG_0680.CR3" -quality 90 -unsharp 0.5x0.5+1.25+0.0 -thumbnail 120x120 -auto-orient "/thumbs/Matt/3-13-24_2/IMG_0680_s.JPG"

Docker image on Unraid. v4.1.1.0

**Comment by Webreaper** [comment]
Are you able to attach the image to this issue (or email to info@damselfly.info) so I can test on my installation?

**Comment by terath199** [comment]
Sure, I had to pick one that worked within the file size limit, but this is happening to all CR3 files. 
[IMG_0201.zip](https://github.com/Webreaper/Damselfly/files/14604615/IMG_0201.zip)

**Comment by Webreaper** [comment]
Okay, interesting - looks like it works on my Mac, but not on my linux box. I suspect there's an add-in I need to include with the version of imagemagick I build for the base container. Let me investigate.

**Comment by Webreaper** [comment]
Okay, so I built a new base image with a rebuilt imagemagick that includes lib-raw, which apparently should support CR3. But when I run the new image (`webreaper/damselfly:dev`) it still doesn't work.

Running `convert identify -list formats` in the container, it states CR3 is supported. So I've no idea. May have to raise an issue on the ImageMagick github.

**Comment by Webreaper** [comment]
Weird thing is, it was confirmed as working in #516. I wonder if there's more than one variant of CR3?

**Comment by Webreaper** [comment]
Okay, so I've pushed a version to dev which now works for me. Please can you try it and confirm?

**Comment by terath199** [comment]
> Okay, so I've pushed a version to dev which now works for me. Please can you try it and confirm?

That did it! Everything is showing up correctly now. Thank you!!!
