### ISSUE TITLE
Thumbnail Mismatch

### ISSUE THREAD

**Issue by grainsoflight** [Webreaper/Damselfly#521]
There seems to be an issue in the more recent releases with a thumbnail mismatch. Clicking an image displays the keywords associated with the full size image in the sidebar, but the thumbnail does not match the full size image. Happens sporadically, not to every image, but is not resolved with a browser refresh.

**Comment by Webreaper** [comment]
I've never seen this.
1. Are you using background thumbnail generation, or on-demand?
2. Have you tried explicitly regenerating the thumbnails to ensure they're up to date?
3. Have you tried shift-Refresh, as it's possible the images may be being cached too heavily be Chrome. I do some cache-busting, but perhaps something else is going on.

**Comment by grainsoflight** [comment]
Regenerating the individual thumbnail fixed it, though I currently have no way to see how many images are affected by the issue because search is not functioning. Do you think background thumbnails would resolve the issue?

**Comment by grainsoflight** [comment]
I turned background thumbnails on and set the system to regenerate thumbnails, and it replaced the one I had corrected with the incorrect thumbnail again

**Comment by grainsoflight** [comment]
It looks like it reverted while the process was running, but was corrected again when the entire process finished
