### ISSUE TITLE
Metadata Scan Not Completing

### ISSUE THREAD

**Issue by grainsoflight** [Webreaper/Damselfly#523]
Running a metadata scan on the full library is only returning keywords and other metadata for a portion of the library before completing. Files have been checked with Metadata++ and Adobe Bridge to confirm that the keywords do in fact exist in the files, but this information does not appear in Damselfly. Metadata format is uniform across every image in the library, so you would think if It can read one it would read all, but it never seems to populate metadata fields for certain images

**Comment by Webreaper** [comment]
Never seen this. Anything in the logs to indicate that there's errors during metadata scanning or other parts of the process?

You mention in the other issue that you're seeing errors about invalid metadata - it's likely the same underlying cause, right?

**Comment by grainsoflight** [comment]
> Never seen this. Anything in the logs to indicate that there's errors during metadata scanning or other parts of the process?
> 
> You mention in the other issue that you're seeing errors about invalid metadata - it's likely the same underlying cause, right?

Possibly? I really dont know how to get around it. These are thousands of family photos that were all created with the same two scanners in the same way. They are all cataloged in lightroom, and at the end of evenings spent tagging, captioning and dating images, I write the all of the metadata to the files at the same time. So I am not entirely sure why a chunk of them are showing an issue, but the rest are not.

**Comment by grainsoflight** [comment]
I exported everything as new PNG files and honestly I think it made it worse, I am seeing more of the "Observed multiple instances of PNG chunk 'iCCP', for which multiples are not allowed" notifications than I did previously

**Comment by grainsoflight** [comment]
I can confirm that for files with that error, no metadata appears in the front end, including keywords

**Comment by Webreaper** [comment]
Can you attach an example of a file that triggers that error and I'll see if I can repro and get the metadata scanner fixed for it?
