### ISSUE TITLE
Add option to collapse all subdirectories by default

### ISSUE THREAD

**Issue by geojed** [Webreaper/Damselfly#525]
To navigate large, deeply nested directory structures, it would be helpful if there was an option to by default only display top-level directory in the tree and manually expand subdirectories from there (or even an option to select/collapse multiple directories at once). See example of desired default behavior below. 

Current default tree
![Uncollapsed](https://github.com/Webreaper/Damselfly/assets/46304487/760f2dd6-fc95-4369-adfe-b700e26ef027)
Desired tree
![Collapsed](https://github.com/Webreaper/Damselfly/assets/46304487/5e9b8a73-f022-400b-92ee-cf6e73c5418e)

**Comment by Webreaper** [comment]
Can you try pulling `webreaper/damselfly:dev` (once [this build](https://github.com/Webreaper/Damselfly/actions/runs/8705457297) has completed) and see if it does what you need?

It should:
- Persist the expanded state of each folder
- Give you a right-click context menu option to expand or collapse all children of a particular folder.
