### ISSUE TITLE
Image orientation not being honoured for image

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly#530]
Per @marijnv2000 : 
File is too big to attach here.. See google drive link:
https://drive.google.com/file/d/1Tz6MqP_AWPCO5x7Yc1AC8eXbhLmwNLR6/view?usp=sharing

exiftool shows "Rotate 270 CW". Local image viewers open it up with the correct orientation, damselfly shows it sideways like this:

![image](https://github.com/Webreaper/Damselfly/assets/17097054/58556bca-d429-4ed6-a4b1-dab01563a365)

**Comment by Webreaper** [comment]
I''ve put in a temporary fix, which should solve your issue. @marijnv2000 can you pull `webreaper/damselfly:dev` and see if it solves it?

**Comment by marijnv2000** [comment]
@Webreaper sorry, took a while for me to get back to this. Thanks for looking into this.

I've changed to dev and it still doesn't rotate the image, neither in the thumbnail or when viewing the image. It does look to have solved the stretching issue for the thumbnail however, it now looks like this:
![image](https://github.com/Webreaper/Damselfly/assets/17097054/c841a74c-95cf-4081-a791-2b97d3df3dab)

By the way, I'm happy to wait for the SkiaSharp issue to be fixed.

**Comment by Webreaper** [comment]
Did you refresh the thumbnails via the context menu? They won't be regenerated unless you do. It works fine for me.

**Comment by Webreaper** [comment]
One other thing to try is pressing shift+refresh in the browser. It could be browser caching.

**Comment by marijnv2000** [comment]
Tried clearing cookies and site data for the domain, tried force refresh, tried private mode, tried a different browser that had never opened Damselfly before, and get the same result on all..

**Comment by Webreaper** [comment]
Dammit. Weird, wonder how it works for me?

**Comment by marijnv2000** [comment]
Weird indeed.. Any way to verify we're running the same code? I pulled the dev tag and saw some changes (notably the + on folder icons letting me expand/collapse them) so I assumed it worked correctly.

**Comment by Webreaper** [comment]
Definitely running the same code. I always run dev.

Possibly an OS thing, I haven't tried it on linux.
