### ISSUE TITLE
Unable to login after initial setup

### ISSUE THREAD

**Issue by Badwolf369** [Webreaper/Damselfly#533]
I just installed Damselfly and was poking around the settings when I found the option to require logging in. I checked it and then it kicked me to a login page and now I am unable to login or do anything. Every time I try to login it just says:

`An error occurred. Please check the Damselfly logs and reload the page.`

The error that accompanies this in the logs is:

`HTTP Exception: net_http_message_not_success_statuscode_reason, 400, Bad Request (api/Login)` [Full Stack Trace](https://pastebin.com/E6eHr922)

Weirdly, I've also tried completely uninstalling damselfly and I can't get it to land back on that initial start screen, it always lands on the login screen.

**Comment by Webreaper** [comment]
Unsure, never seen this before. Can you try clearing all your cookies etc on the client?

**Comment by Badwolf369** [comment]
I'm unsure what exactly caused the inability to log in, but the issue with reinstalling was it turned out I had the wrong volume mounted. Changing to the correct volume cleared the issue, and now I can clear the volume if the issue reappears.
