### ISSUE TITLE
Possebility to show Metadata from PNG files

### ISSUE THREAD

**Issue by baalspawn** [Webreaper/Damselfly#537]
Hi, I was wondering if there is a possebility to add an option to read the metadata for PNG files.
This would be very nice especially for those who make Stable Diffusion images.

Both A1111 and ComfyUI store a lot of data in the Chunk section of the Metadata.
Here you can retrieve prompt, model and settings used to generate the image.

So the "simple" version would be to just be able to show the meta data same way the png file inspector does.
A pretty version would be more difficult due to the different ways the stable diffusions programs store their info.

Example of a simple workflow in ComfyUI:
![image](https://github.com/user-attachments/assets/817d5168-b075-4395-aa30-98127166d83d)

My current workflow when I forget how the image was made (and unable to use the workflow) is using an online PNG inspector
ref: https://www.nayuki.io/page/png-file-chunk-inspector

For A1111 the following chunks are of interest:
iTXt or tEXt
(ref: https://www.w3.org/TR/2003/REC-PNG-20031110/#11iTXt)

For ComfyUI it is nice to have the following data:
tEXt
(ref: https://www.w3.org/TR/2003/REC-PNG-20031110/#11tEXt) 

Not sure if the IHDR chunk is needed since Damselfly already knows the image properties.
(ref: https://www.w3.org/TR/2003/REC-PNG-20031110/#11IHDR)

Eks of the chunk data:

Example from a ComfyUI with workflow attatched:
![SDFX_00001_](https://github.com/user-attachments/assets/4a02e190-1ceb-4f6d-8d3d-61a2f446c6f8)
![image](https://github.com/user-attachments/assets/cbdea8bd-b254-4c4d-83af-5d2e31bac8cb)
![image](https://github.com/user-attachments/assets/6a4aa4dd-8a28-43ad-b4f8-c6f857125cb8)
![image](https://github.com/user-attachments/assets/4e4fd6a5-43a1-44db-9887-d8babae62418)
The image is longer, had to cut it short ;)

Example from a Stable Diffusion Webui Forge:

Made with Stable Diffusion WebUI Forge
![00000-1527653760](https://github.com/user-attachments/assets/46a570af-1ee3-465d-bb58-3491776770fd)
![image](https://github.com/user-attachments/assets/9a2e2e86-7ab8-4067-b90b-92b3a4c0115c)

**Comment by Webreaper** [comment]
Thanks, I'll take a look. I use [MetadataExtractor](https://github.com/drewnoakes/metadata-extractor-dotnet) so shouldn't have to worry about the binary data etc. 

What would be useful is if you could run [ExifTool](https://exiftool.org/) over the sample images and from the output, give me the names and values of the fields you're particularly interested in. I can then look at what they're mapped to and add the code to extract them. :)

**Comment by Webreaper** [comment]
Okay, I've had a look at this briefly, and added code to display the prompt in damselfly's Caption fielfd. Hope that helps.
