### ISSUE TITLE
Typo "Recognised" should be "Recognized"

### ISSUE THREAD

**Issue by vloschiavo** [Webreaper/Damselfly#542]
In the Damselfly Information page, there is a typo in the word Recognized:

System
.Net Version:	v8.0.3
OS Version:	Other 1.0.0.0
Client Runtime:	Wasm
Server Architecture:	Unix 6.8.0.40 (X64)
Processor Count:	1
Photo Collection
Folders:	3343
Images:	122668
Image File Size:	110.11 GB
Tags/Keywords:	176
**Recognised** Objects:	53973
Faces:	5493
People Identified:	48
Process Queue
Pending Metadata Scans:	5
Pending Thumbnails:	0
Pending AI Scans:	94063
Pending Keyword Updates:	10 (total keywords: 10)

**Comment by vloschiavo** [comment]
Submitted Pull Request #543

**Comment by Webreaper** [comment]
Erm, no. That's the US spelling, which is wrong.
