### ISSUE TITLE
i'm unable to pass any photo folders into it using docker

### ISSUE THREAD

**Issue by jill88** [Webreaper/Damselfly#544]
I've tried all the usual syntax variations, but I can't get any photos (folders) to show up in damselfy docker installation.  It usually works on other apps I've tried.  I'm using docker on Windows with fstab mounting on the wsl2 vm.  here is my docker compose....

```services:
  damselfly:
    container_name: damselfly
    image: webreaper/damselfly
    ports:
      - 6363:6363/tcp
    volumes:
      - ./config:/config
      - ./thumbs/thumbs:/thumbs
      - //wsl$/Ubuntu-22.04/mnt/winshare1/familyphotos1:/pictures
    restart: unless-stopped```

I've tried forward slash, back slash...mounting to a drive letter.  I even tried just a local folder on c drive, nothing gets detected.  Please advise.  Thank you.

**Comment by Webreaper** [comment]
Damselfly doesn't support docker on Windows. 

https://github.com/Webreaper/Damselfly/blob/master/docs/Installation.md#can-i-run-damselfly-without-docker
