### ISSUE TITLE
TaskCancelled Exception logged when scrolling Virtualized folder list

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/Damselfly#72]
https://github.com/dotnet/aspnetcore/issues/28280#

**Comment by Liero** [comment]
It seems to be reproducible, when there is a Task.Delay in the ItemsProvider callback:

       private async ValueTask<ItemsProviderResult<Item>> ProvideItems(ItemsProviderRequest request)
       {

              using var db = _dbContextFactory.CreateDbContext();
              await Task.Delay(200, request.CancellationToken);
              var items = await db.Items.Skip(request.StartIndex)
                    .Take(request.Count)
                    .ToArrayAsync(request.CancellationToken);
              return new ItemsProviderResult<Item>(items,  await db.Items.CountAsync());
       }

**Comment by Webreaper** [comment]
Nice. Want to post that to the aspcore project/issue above? Then somebody at MSFT. Might fix it. 😁

**Comment by Webreaper** [comment]
I think this issue may be fixed in .Net 6 RC1 - I don't remember seeing it for a while...
